#lang racket
(require rackunit
         cpsc411/langs/v8
         cpsc411/compiler-lib
         cpsc411/ptr-run-time
         "../test-common.rkt"
         (only-in "../generate-x64.rkt" generate-x64))

(define (check-paren-x64-v7 p)
  (if (paren-x64-v8? p) p #f))

(define (check-execute p)
  ; (if (execute? p) p #f)
  p)

(define (ptr->v/generate-x64 p)
;   (define v (ptr->v/p3yaz p))
;   (if (equal? v (void)) 
;     eof
;     v)
    p
    )

(define-syntax-rule (check-by-interp p)
  (parameterize ([current-pass-list (list wrap-x64-run-time wrap-x64-boilerplate)])
    (check-equal? (ptr->v/generate-x64 (interp-paren-x64-v8 (check-paren-x64-v8 p)))
       (execute (generate-x64 p)))))
       
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! rax 8)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! rax 6)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! rax 14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! rax 13102)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! rax 18990)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! rax 30)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rsi 0)
                    (set! rdi 0)
                    (set! r15 r15)
                    (jump L.+.1)
                    (with-label L.+.1 (set! r15 r15))
                    (set! r13 rdi)
                    (set! r14 rsi)
                    (set! r9 r14)
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.10)
                    (jump L.tmp.11)
                    (with-label L.tmp.10 (set! r9 14))
                    (jump L.tmp.12)
                    (with-label L.tmp.11 (set! r9 6))
                    (jump L.tmp.12)
                    (with-label L.tmp.12 (compare r9 6))
                    (jump-if != L.__nested.3)
                    (jump L.__nested.4)
                    (with-label L.tmp.7 (set! r9 14))
                    (jump L.tmp.9)
                    (with-label L.tmp.8 (set! r9 6))
                    (jump L.tmp.9)
                    (with-label L.tmp.9 (compare r9 6))
                    (jump-if != L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.5 (set! r13 r13))
                    (set! r13 (+ r13 r14))
                    (set! rax r13)
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 574))
                    (jump r15)
                    (with-label L.__nested.3 (set! r9 r13))
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.7)
                    (jump L.tmp.8)
                    (with-label L.__nested.4 (set! rax 574))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rdi 6)
                    (set! r15 r15)
                    (jump L.not.1)
                    (with-label L.not.1 (set! r15 r15))
                    (set! r14 rdi)
                    (compare r14 6)
                    (jump-if != L.__nested.3)
                    (jump L.__nested.4)
                    (with-label L.__nested.3 (set! rax 6))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 14))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rdi 14)
                    (set! r15 r15)
                    (jump L.not.1)
                    (with-label L.not.1 (set! r15 r15))
                    (set! r14 rdi)
                    (compare r14 6)
                    (jump-if != L.__nested.3)
                    (jump L.__nested.4)
                    (with-label L.__nested.3 (set! rax 6))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 14))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! r14 6)
                    (jump L.__nested.2)
                    (with-label L.__nested.1 (set! rax 22))
                    (jump r15)
                    (with-label L.__nested.2 (set! rax 0))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rdi 14)
                    (set! r15 r15)
                    (jump L.fixnum?.1)
                    (with-label L.fixnum?.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 7))
                    (set! r14 r14)
                    (compare r14 0)
                    (jump-if = L.__nested.3)
                    (jump L.__nested.4)
                    (with-label L.__nested.3 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 6))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rdi 30)
                    (set! r15 r15)
                    (jump L.error?.1)
                    (with-label L.error?.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 62)
                    (jump-if = L.__nested.3)
                    (jump L.__nested.4)
                    (with-label L.__nested.3 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 6))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rdi 22)
                    (set! r15 r15)
                    (jump L.fixnum?.1)
                    (with-label L.fixnum?.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 7))
                    (set! r14 r14)
                    (compare r14 0)
                    (jump-if = L.__nested.3)
                    (jump L.__nested.4)
                    (with-label L.__nested.3 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 6))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rdi 14)
                    (set! r15 r15)
                    (jump L.ascii-char?.1)
                    (with-label L.ascii-char?.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 46)
                    (jump-if = L.__nested.3)
                    (jump L.__nested.4)
                    (with-label L.__nested.3 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 6))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rdi 30)
                    (set! r15 r15)
                    (jump L.boolean?.1)
                    (with-label L.boolean?.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 247))
                    (set! r14 r14)
                    (compare r14 6)
                    (jump-if = L.__nested.3)
                    (jump L.__nested.4)
                    (with-label L.__nested.3 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 6))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rdi 30)
                    (set! r15 r15)
                    (jump L.ascii-char?.1)
                    (with-label L.ascii-char?.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 46)
                    (jump-if = L.__nested.3)
                    (jump L.__nested.4)
                    (with-label L.__nested.3 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 6))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 6)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 25646)
                    (set! r13 28206)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rdi 8)
                    (set! r15 r15)
                    (jump L.void?.2)
                    (with-label L.void?.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 30)
                    (jump-if = L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.__nested.4 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax 6))
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! rax 14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rsi 0)
                    (set! rdi 0)
                    (set! r15 r15)
                    (jump L.<=.2)
                    (with-label L.<=.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r9 r13)
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.13)
                    (jump L.tmp.14)
                    (with-label L.tmp.13 (set! r9 14))
                    (jump L.tmp.15)
                    (with-label L.tmp.14 (set! r9 6))
                    (jump L.tmp.15)
                    (with-label L.tmp.15 (compare r9 6))
                    (jump-if != L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.tmp.10 (set! r9 14))
                    (jump L.tmp.12)
                    (with-label L.tmp.11 (set! r9 6))
                    (jump L.tmp.12)
                    (with-label L.tmp.12 (compare r9 6))
                    (jump-if != L.__nested.6)
                    (jump L.__nested.7)
                    (with-label L.__nested.8 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.9 (set! rax 6))
                    (jump r15)
                    (with-label L.__nested.6 (compare r14 r13))
                    (jump-if <= L.__nested.8)
                    (jump L.__nested.9)
                    (with-label L.__nested.7 (set! rax 1342))
                    (jump r15)
                    (with-label L.__nested.4 (set! r9 r14))
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.10)
                    (jump L.tmp.11)
                    (with-label L.__nested.5 (set! rax 1342))
                    (jump r15)
                    (with-label L.tmp.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax 14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 6)
                    (set! r14 22)
                    (set! r14 1086429096)
                    (set! rax 22)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rax 14)
                    (jump r15)
                    (with-label L.x.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax -3961536528)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rax 6)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! rax 8)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rax 19502)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax 30)
                    (jump r15)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! rax 22)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! r14 19246)
                    (jump L.__nested.2)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! rax 6)
                    (jump r15)
                    (with-label L.__nested.2 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.3 (set! rax 30))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rsi 8)
                    (set! rdi 24878)
                    (set! r15 r15)
                    (jump L.eq?.2)
                    (with-label L.eq?.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (compare r14 r13)
                    (jump-if = L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.__nested.4 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax 6))
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rsi 0)
                    (set! rdi 8)
                    (set! r15 r15)
                    (jump L.*.2)
                    (with-label L.*.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r9 r13)
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.11)
                    (jump L.tmp.12)
                    (with-label L.tmp.11 (set! r9 14))
                    (jump L.tmp.13)
                    (with-label L.tmp.12 (set! r9 6))
                    (jump L.tmp.13)
                    (with-label L.tmp.13 (compare r9 6))
                    (jump-if != L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.tmp.8 (set! r9 14))
                    (jump L.tmp.10)
                    (with-label L.tmp.9 (set! r9 6))
                    (jump L.tmp.10)
                    (with-label L.tmp.10 (compare r9 6))
                    (jump-if != L.__nested.6)
                    (jump L.__nested.7)
                    (with-label L.__nested.6 (set! r13 r13))
                    (set! r13 (arithmetic-shift-right r13 3))
                    (set! r13 r13)
                    (set! r14 r14)
                    (set! r14 (* r14 r13))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.__nested.7 (set! rax 318))
                    (jump r15)
                    (with-label L.__nested.4 (set! r9 r14))
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.8)
                    (jump L.tmp.9)
                    (with-label L.__nested.5 (set! rax 318))
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r13 r8)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rax 22)
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rax 14)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rax 6)
                    (jump r15)
                    (with-label L.func.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rsi 1871355128)
                    (set! rdi 27950)
                    (set! r15 r15)
                    (jump L.eq?.2)
                    (with-label L.eq?.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (compare r14 r13)
                    (jump-if = L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.__nested.4 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax 6))
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! rax 14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rax 30)
                    (jump r15)
                    (with-label L.x.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rax 8)
                    (jump r15)
                    (with-label L.func.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! rax 14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! r14 6)
                    (set! r14 22)
                    (set! r14 22)
                    (set! rax 0)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rax 6)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax 6)
                    (jump r15)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! r14 30)
                    (set! r14 22)
                    (set! r14 0)
                    (set! r14 0)
                    (set! rax 14)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rax 29230)
                    (jump r15)
                    (with-label L.x.0.1 (set! r15 r15))
                    (set! rax 22)
                    (jump r15)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rax 22)
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rax 6)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! r14 25902)
                    (jump L.__nested.3)
                    (with-label L.tmp.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax 6)
                    (jump r15)
                    (with-label L.__nested.3 (set! rax 30))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 22))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rdi 13102)
                    (set! r15 r15)
                    (jump L.void?.3)
                    (with-label L.void?.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 30)
                    (jump-if = L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.5 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 6))
                    (jump r15)
                    (with-label L.x.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 0)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rax 14)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! rax 30)
                    (jump r15)
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.tmp.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rax 30)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax 6)
                    (jump r15)
                    (with-label L.func.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! rax 22574)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rdi 22)
                    (set! r15 r15)
                    (jump L.boolean?.3)
                    (with-label L.boolean?.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 247))
                    (set! r14 r14)
                    (compare r14 6)
                    (jump-if = L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.5 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 6))
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rax 27694)
                    (jump r15)
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax 14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.7 (set! (rbp - 0) r15))
                    (set! rbp (- rbp 8))
                    (set! rsi 0)
                    (set! rdi 22)
                    (set! r15 L.rp.3)
                    (jump L.eq?.1)
                    (with-label L.ascii-char?.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 46)
                    (jump-if = L.__nested.8)
                    (jump L.__nested.9)
                    (with-label L.__nested.8 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.9 (set! rax 6))
                    (jump r15)
                    (with-label L.eq?.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (compare r14 r13)
                    (jump-if = L.__nested.10)
                    (jump L.__nested.11)
                    (with-label L.__nested.10 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.11 (set! rax 6))
                    (jump r15)
                    (with-label L.rp.3 (set! rbp (+ rbp 8)))
                    (set! r15 rax)
                    (set! r14 6)
                    (set! r14 2031626432)
                    (set! r14 14)
                    (jump L.tmp.4)
                    (with-label L.tmp.4 (set! r15 30))
                    (jump L.tmp.6)
                    (with-label L.tmp.5 (set! r15 r15))
                    (jump L.tmp.6)
                    (with-label L.tmp.6 (set! rdi r15))
                    (set! r15 (rbp - 0))
                    (jump L.ascii-char?.2)))
(check-by-interp '(begin
                    (with-label L.__main.6 (set! r15 r15))
                    (set! r14 30)
                    (jump L.__nested.4)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax 22)
                    (jump r15)
                    (with-label L.func.2.3 (set! r15 r15))
                    (set! rax 6)
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 30))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax 29230))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rdi 6)
                    (set! r15 r15)
                    (jump L.ascii-char?.3)
                    (with-label L.ascii-char?.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 46)
                    (jump-if = L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.5 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 6))
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax 6)
                    (jump r15)
                    (with-label L.func.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rax 6)
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 14)
                    (jump r15)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rdi 20526)
                    (set! r15 r15)
                    (jump L.ascii-char?.3)
                    (with-label L.ascii-char?.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 46)
                    (jump-if = L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.5 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 6))
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax 14)
                    (jump r15)
                    (with-label L.func.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! rax 6)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! r14 22)
                    (set! r14 6)
                    (set! rax 22)
                    (jump r15)
                    (with-label L.x.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax 0)
                    (jump r15)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rdi 30)
                    (set! r15 r15)
                    (jump L.boolean?.3)
                    (with-label L.boolean?.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 247))
                    (set! r14 r14)
                    (compare r14 6)
                    (jump-if = L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.5 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 6))
                    (jump r15)
                    (with-label L.tmp.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 0)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rdi 30)
                    (set! r15 r15)
                    (jump L.ascii-char?.3)
                    (with-label L.ascii-char?.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 46)
                    (jump-if = L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.5 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 6))
                    (jump r15)
                    (with-label L.x.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax -3529966152)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! r14 14)
                    (set! rsi 8)
                    (set! rdi 4105232688)
                    (set! r15 r15)
                    (jump L.*.4)
                    (with-label L.*.4 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r9 r13)
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.13)
                    (jump L.tmp.14)
                    (with-label L.tmp.13 (set! r9 14))
                    (jump L.tmp.15)
                    (with-label L.tmp.14 (set! r9 6))
                    (jump L.tmp.15)
                    (with-label L.tmp.15 (compare r9 6))
                    (jump-if != L.__nested.6)
                    (jump L.__nested.7)
                    (with-label L.tmp.10 (set! r9 14))
                    (jump L.tmp.12)
                    (with-label L.tmp.11 (set! r9 6))
                    (jump L.tmp.12)
                    (with-label L.tmp.12 (compare r9 6))
                    (jump-if != L.__nested.8)
                    (jump L.__nested.9)
                    (with-label L.__nested.8 (set! r13 r13))
                    (set! r13 (arithmetic-shift-right r13 3))
                    (set! r13 r13)
                    (set! r14 r14)
                    (set! r14 (* r14 r13))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.__nested.9 (set! rax 318))
                    (jump r15)
                    (with-label L.__nested.6 (set! r9 r14))
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.10)
                    (jump L.tmp.11)
                    (with-label L.__nested.7 (set! rax 318))
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rax 14)
                    (jump r15)
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.func.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rax 0)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rax 0)
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax 14)
                    (jump r15)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax 14)
                    (jump r15)
                    (with-label L.x.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 6)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rax 22)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! rax 22)
                    (jump r15)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! rax 14)
                    (jump r15)
                    (with-label L.x.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! rdi 8)
                    (set! r15 r15)
                    (jump L.empty?.3)
                    (with-label L.empty?.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 22)
                    (jump-if = L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.5 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 6))
                    (jump r15)
                    (with-label L.tmp.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! r13 r9)
                    (set! r13 (rbp - 0))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 6)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.6 (set! r15 r15))
                    (set! r14 6)
                    (jump L.__nested.5)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 8)
                    (jump r15)
                    (with-label L.func.1.2 (set! r15 r15))
                    (set! rax 14)
                    (jump r15)
                    (with-label L.fn.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax 22))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! rdi 8)
                    (set! r15 r15)
                    (jump L.ascii-char?.4)
                    (with-label L.ascii-char?.4 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 46)
                    (jump-if = L.__nested.6)
                    (jump L.__nested.7)
                    (with-label L.__nested.6 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.7 (set! rax 6))
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! r13 r9)
                    (set! r13 (rbp - 0))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.tmp.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! rax 6)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! rdi 6)
                    (set! r15 r15)
                    (jump L.boolean?.4)
                    (with-label L.boolean?.4 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 247))
                    (set! r14 r14)
                    (compare r14 6)
                    (jump-if = L.__nested.6)
                    (jump L.__nested.7)
                    (with-label L.__nested.6 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.7 (set! rax 6))
                    (jump r15)
                    (with-label L.tmp.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.x.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! rax 8)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! rdi 22)
                    (set! r15 r15)
                    (jump L.ascii-char?.4)
                    (with-label L.ascii-char?.4 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 46)
                    (jump-if = L.__nested.6)
                    (jump L.__nested.7)
                    (with-label L.__nested.6 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.7 (set! rax 6))
                    (jump r15)
                    (with-label L.tmp.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r13 (rbp - 0))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax 0)
                    (jump r15)
                    (with-label L.func.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! rax 8)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.7 (set! (rbp - 0) r15))
                    (set! rbp (- rbp 8))
                    (set! rsi 6)
                    (set! rdi 8)
                    (set! r15 L.rp.6)
                    (jump L.eq?.4)
                    (with-label L.<.5 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r9 r13)
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.17)
                    (jump L.tmp.18)
                    (with-label L.tmp.17 (set! r9 14))
                    (jump L.tmp.19)
                    (with-label L.tmp.18 (set! r9 6))
                    (jump L.tmp.19)
                    (with-label L.tmp.19 (compare r9 6))
                    (jump-if != L.__nested.8)
                    (jump L.__nested.9)
                    (with-label L.tmp.14 (set! r9 14))
                    (jump L.tmp.16)
                    (with-label L.tmp.15 (set! r9 6))
                    (jump L.tmp.16)
                    (with-label L.tmp.16 (compare r9 6))
                    (jump-if != L.__nested.10)
                    (jump L.__nested.11)
                    (with-label L.__nested.12 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.13 (set! rax 6))
                    (jump r15)
                    (with-label L.__nested.10 (compare r14 r13))
                    (jump-if < L.__nested.12)
                    (jump L.__nested.13)
                    (with-label L.__nested.11 (set! rax 1086))
                    (jump r15)
                    (with-label L.__nested.8 (set! r9 r14))
                    (set! r9 (bitwise-and r9 7))
                    (set! r9 r9)
                    (compare r9 0)
                    (jump-if = L.tmp.14)
                    (jump L.tmp.15)
                    (with-label L.__nested.9 (set! rax 1086))
                    (jump r15)
                    (with-label L.eq?.4 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (compare r14 r13)
                    (jump-if = L.__nested.20)
                    (jump L.__nested.21)
                    (with-label L.__nested.20 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.21 (set! rax 6))
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! rax 14)
                    (jump r15)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax 6)
                    (jump r15)
                    (with-label L.x.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! rax 0)
                    (jump r15)
                    (with-label L.rp.6 (set! rbp (+ rbp 8)))
                    (set! r15 rax)
                    (set! rsi 8)
                    (set! rdi -2229142488)
                    (set! r15 (rbp - 0))
                    (jump L.<.5)))
(check-by-interp '(begin
                    (with-label L.__main.8 (set! (rbp - 0) r15))
                    (set! r15 30)
                    (jump L.__nested.6)
                    (with-label L.empty?.4 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 255))
                    (set! r14 r14)
                    (compare r14 22)
                    (jump-if = L.__nested.9)
                    (jump L.__nested.10)
                    (with-label L.__nested.9 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.10 (set! rax 6))
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! rax 6)
                    (jump r15)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rax 6)
                    (jump r15)
                    (with-label L.fn.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 14)
                    (jump r15)
                    (with-label L.rp.5 (set! rbp (+ rbp 8)))
                    (set! r15 rax)
                    (set! rax r15)
                    (set! r10 (rbp - 0))
                    (jump r10)
                    (with-label L.__nested.6 (set! rbp (- rbp 8)))
                    (set! rdi 6)
                    (set! r15 L.rp.5)
                    (jump L.empty?.4)
                    (with-label L.__nested.7 (set! rax 8))
                    (set! r10 (rbp - 0))
                    (jump r10)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! rdi 6)
                    (set! r15 r15)
                    (jump L.fixnum?.4)
                    (with-label L.fixnum?.4 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 r14)
                    (set! r14 (bitwise-and r14 7))
                    (set! r14 r14)
                    (compare r14 0)
                    (jump-if = L.__nested.6)
                    (jump L.__nested.7)
                    (with-label L.__nested.6 (set! rax 14))
                    (jump r15)
                    (with-label L.__nested.7 (set! rax 6))
                    (jump r15)
                    (with-label L.x.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! r13 r9)
                    (set! r13 (rbp - 0))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! rax 0)
                    (jump r15)
                    (with-label L.tmp.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 6)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! r14 22)
                    (set! r14 22)
                    (set! r14 19502)
                    (set! rax 29230)
                    (jump r15)
                    (with-label L.tmp.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! r13 r9)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! rax 2370093256)
                    (jump r15)
                    (with-label L.tmp.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! r14 30)
                    (set! r14 21550)
                    (set! r14 22)
                    (set! r14 22)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! rax 8)
                    (jump r15)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! r13 r9)
                    (set! r13 (rbp - 0))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.x.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! rax 6)
                    (jump r15)))
;;; Added by Trevor on 2026-03-19
